services:
  tcn-gan:
    build:
      context: .
      args:
        UID: ${UID}
        GID: ${GID}
        COMMANDS_PATH: ${COMMANDS_PATH}
    working_dir: /tcn-gan
    volumes:
      - ./:/tcn-gan
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    ulimits:
      memlock: -1
      stack: 67108864
    ipc: host
    command: ${COMMANDS_PATH}